/**
 * fireyejsRunner — Token generation and infrastructure.
 *
 * bx-ua: Generated by bxUaGenerator.ts — a pure Node.js implementation
 *   that replicates the AWSC fireyejs.js token format without Playwright.
 *   Matches the real token: "231!" + base64(900 bytes) = 1204 chars.
 *
 * bx-pp: SHA-256 payload hash fallback (opcode 58 needs real AWSC).
 *
 * Cookie refresh: Playwright browser navigates chat.qwen.ai to refresh
 *   acw_tc and other WAF session cookies. This is the only remaining
 *   browser dependency — runs once per 30 min per account.
 */
import type { Browser, BrowserContext } from 'playwright';
import {
  getBrowserContextOptions,
  getChromiumLaunchOptions,
  getCookieNames,
  mergeCookieHeaders,
  parseCookieHeader,
} from './browserRuntime.ts';
import { getBxUaToken } from './bxUaGenerator.ts';
import { logStore } from './logStore.ts';
import { QWEN_API_BASE } from './qwen.ts';
import { tokenCache } from './tokenCache.ts';

// ─── Constants ───────────────────────────────────────────────────────────────

const BX_UA_TTL_MS = 15 * 60 * 1000; // 15 min
// ─── bx-ua generation ────────────────────────────────────────────────────────
// Pure Node.js via bxUaGenerator.ts — no browser needed.
// Token matches real AWSC fireyejs.js output format exactly.

/**
 * Generate (or retrieve cached) bx-ua token.
 *
 * @returns The bx-ua token string (e.g. "231!<base64>") or null
 */
export async function generateBxUa(): Promise<string | null> {
  // Check shared cache first
  const cached = tokenCache.get('bx-ua');
  if (cached) return cached;

  try {
    const token = getBxUaToken();

    if (token && token.startsWith('231!')) {
      tokenCache.set('bx-ua', token, BX_UA_TTL_MS);
      logStore.log('info', 'fireyejs', `bx-ua generated via bxUaGenerator (${token.length} chars, TTL ${BX_UA_TTL_MS / 60000} min)`);
      return token;
    }

    logStore.log('warn', 'fireyejs', 'bx-ua generated but invalid format');
    return null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logStore.log('error', 'fireyejs', `bx-ua generation failed: ${msg}`);
    return null;
  }
}

// ─── bx-pp generation (Phase C) ──────────────────────────────────────────────

/**
 * Generate a bx-pp per-request signature.
 *
 * bx-pp is normally generated by fireyejs opcode 58. Since the real fireyejs
 * requires the AWSC browser environment, we use a SHA-256 payload hash as
 * fallback. Testing confirmed this works: the models endpoint returned 200.
 *
 * TODO: reverse-engineer opcode 58 from fireyejs.js for bx-pp generation
 * that matches what the real browser produces.
 */
export async function generateBxPp(payload?: string): Promise<string | null> {
  // ponytail: hash fallback until opcode 58 reverse-engineered
  try {
    const data = new TextEncoder().encode(payload || Date.now().toString());
    const hash = await crypto.subtle.digest('SHA-256', data);
    const hashHex = Array.from(new Uint8Array(hash))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
      .slice(0, 32);
    logStore.log('debug', 'fireyejs', 'bx-pp generated (hash fallback)');
    return hashHex;
  } catch {
    return null;
  }
}

// ─── Cookie refresh via browser ─────────────────────────────────────────────

let playwrightBrowser: Browser | null = null;

async function getBrowser(): Promise<Browser> {
  if (playwrightBrowser?.isConnected()) {
    return playwrightBrowser;
  }
  const { chromium } = await import('playwright');
  playwrightBrowser = await chromium.launch(getChromiumLaunchOptions(true));
  return playwrightBrowser;
}

/**
 * Refresh cookies for an account by navigating chat.qwen.ai in a real browser.
 *
 * @param cookieStr - Current saved cookies (may be stale)
 * @returns Fresh cookie string or null
 */
export async function refreshCookiesViaBrowser(cookieStr: string): Promise<string | null> {
  let context: BrowserContext | null = null;
  try {
    const browser = await getBrowser();
    context = await browser.newContext(getBrowserContextOptions());
    const page = await context.newPage();

    if (cookieStr) {
      const cookies = Array.from(parseCookieHeader(cookieStr), ([name, value]) => ({ name, value, domain: '.qwen.ai', path: '/' }));
      await context.addCookies(cookies).catch(() => {});
    }

    // Better wait strategy
    await page
      .goto(QWEN_API_BASE, {
        waitUntil: 'networkidle',
        timeout: 30000,
      })
      .catch(() => {});

    // Wait for WAF challenge to resolve or page to stabilize
    let stable = false;
    for (let i = 0; i < 20; i++) {
      const html = await page.evaluate(() => document.documentElement?.innerHTML || '').catch(() => '');
      if (!html.includes('aliyun_waf') && html.length > 500) {
        stable = true;
        break;
      }
      await new Promise((r) => setTimeout(r, 800));
    }
    if (!stable) {
      logStore.log('warn', 'fireyejs', 'Page did not stabilize after WAF wait');
    }

    const freshCookieStr = (await context.cookies())
      .filter((cookie) => cookie.name)
      .map((cookie) => `${cookie.name}=${cookie.value}`)
      .join('; ');
    const mergedCookieStr = mergeCookieHeaders(cookieStr, freshCookieStr);

    if (mergedCookieStr) {
      logStore.log('info', 'fireyejs', `Cookies refreshed via browser (${getCookieNames(mergedCookieStr).length} names)`);
      return mergedCookieStr;
    }
    return null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logStore.log('warn', 'fireyejs', `Cookie refresh via browser failed: ${msg.substring(0, 150)}`);
    return null;
  } finally {
    if (context) {
      try {
        await context.close();
      } catch {
        /* ignore */
      }
    }
  }
}
